/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-06-18 11:54:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1494252182481L));
    _jspx_dependants.put("jar:file:/F:/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/WheelskartFront/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<html>\r\n");
      out.write("<head><style>\r\n");
      out.write("/*\r\n");
      out.write("Code snippet by maridlcrmn for Bootsnipp.com\r\n");
      out.write("Follow me on Twitter @maridlcrmn\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write(".navbar-brand { position: relative; z-index: 2; }\r\n");
      out.write("\r\n");
      out.write(".navbar-nav.navbar-right .btn { position: relative; z-index: 2; padding: 4px 20px; margin: 10px auto; transition: transform 0.3s; }\r\n");
      out.write("\r\n");
      out.write(".navbar .navbar-collapse { position: relative; overflow: hidden !important; }\r\n");
      out.write(".navbar .navbar-collapse .navbar-right > li:last-child { padding-left: 22px; }\r\n");
      out.write("\r\n");
      out.write(".navbar .nav-collapse { position: absolute; z-index: 1; top: 0; left: 0; right: 0; bottom: 0; margin: 0; padding-right: 120px; padding-left: 80px; width: 100%; }\r\n");
      out.write(".navbar.navbar-default .nav-collapse { background-color: #f8f8f8; }\r\n");
      out.write(".navbar.navbar-inverse .nav-collapse { background-color: #222; }\r\n");
      out.write(".navbar .nav-collapse .navbar-form { border-width: 0; box-shadow: none; }\r\n");
      out.write(".nav-collapse>li { float: right; }\r\n");
      out.write("\r\n");
      out.write(".btn.btn-circle { border-radius: 50px; }\r\n");
      out.write(".btn.btn-outline { background-color: transparent; }\r\n");
      out.write("\r\n");
      out.write(".navbar-nav.navbar-right .btn:not(.collapsed) {\r\n");
      out.write("    background-color: rgb(111, 84, 153);\r\n");
      out.write("    border-color: rgb(111, 84, 153);\r\n");
      out.write("    color: rgb(255, 255, 255);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar.navbar-default .nav-collapse,\r\n");
      out.write(".navbar.navbar-inverse .nav-collapse {\r\n");
      out.write("    height: auto !important;\r\n");
      out.write("    transition: transform 0.3s;\r\n");
      out.write("    transform: translate(0px,-50px);\r\n");
      out.write("}\r\n");
      out.write(".navbar.navbar-default .nav-collapse.in,\r\n");
      out.write(".navbar.navbar-inverse .nav-collapse.in {\r\n");
      out.write("    transform: translate(0px,0px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 767px) {\r\n");
      out.write("    .navbar .navbar-collapse .navbar-right > li:last-child { padding-left: 15px; padding-right: 15px; } \r\n");
      out.write("    \r\n");
      out.write("    .navbar .nav-collapse { margin: 7.5px auto; padding: 0; }\r\n");
      out.write("    .navbar .nav-collapse .navbar-form { margin: 0; }\r\n");
      out.write("    .nav-collapse>li { float: none; }\r\n");
      out.write("    \r\n");
      out.write("    .navbar.navbar-default .nav-collapse,\r\n");
      out.write("    .navbar.navbar-inverse .nav-collapse s{\r\n");
      out.write("        transform: translate(-100%,0px);\r\n");
      out.write("    }\r\n");
      out.write("    .navbar.navbar-default .nav-collapse.in,\r\n");
      out.write("    .navbar.navbar-inverse .nav-collapse.in {\r\n");
      out.write("        transform: translate(0px,0px);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .navbar.navbar-default .nav-collapse.slide-down,\r\n");
      out.write("    .navbar.navbar-inverse .nav-collapse.slide-down {\r\n");
      out.write("        transform: translate(0px,-100%);\r\n");
      out.write("    }\r\n");
      out.write("    .navbar.navbar-default .nav-collapse.in.slide-down,\r\n");
      out.write("    .navbar.navbar-inverse .nav-collapse.in.slide-down {\r\n");
      out.write("        transform: translate(0px,0px);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav><ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li><a href=\"\"src/main/webapp/WEB-INF/views/Home.jsp\"\">Home</a></li>\r\n");
      out.write("            <li><a href=\"#\">About</a></li>\r\n");
      out.write("            <li><a href=\"#\">Services</a></li>\r\n");
      out.write("            <li><a href=\"#\">Works</a></li>\r\n");
      out.write("            <li><a href=\"#\">News</a></li>\r\n");
      out.write("            <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"btn btn-default btn-outline btn-circle\"  data-toggle=\"collapse\" href=\"#nav-collapse1\" aria-expanded=\"false\" aria-controls=\"nav-collapse1\">Categories</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          \r\n");
      out.write("          <ul class=\"collapse nav navbar-nav nav-collapse\" id=\"nav-collapse1\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("          </nav>\r\n");
      out.write("</body>\r\n");
      out.write("   \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/Header.jsp(89,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("category");
    // /WEB-INF/views/Header.jsp(89,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/Header.jsp(89,12) '${categoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            \r\n");
          out.write("          <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(".jsp\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\r\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
